### PR TITLE
Updated for Python 3 compatibility

### PR DESCRIPTION
**Pull request by rgerkin**
Required for the README instructions in https://github.com/openworm/muscle_model to work in Python 3.

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks for that @rgerkin, but nml.py is generated code, created by [generateDS.py](http://www.davekuhlman.org/generateDS.html). It gets regenerated everytime the schema changes. Ideally generateDS.py would be updated to produce P3 compliant code, but alternatively a quick search replace in the generated file could make the changes. 

Will look into it.

**Comment by rgerkin** [comment]
I've made a pull request for the generateDS repo implementing this change.  I will let you know if they take it.

**Comment by pgleeson** [comment]
Thanks for this. Moving this to an issue here: https://github.com/NeuralEnsemble/libNeuroML/issues/58

**Comment by rgerkin** [comment]
The generateDS source now produces P3 compliant code:  https://bitbucket.org/dkuhlman/generateds/pull-request/13/changes-for-python-3-compatibility/diff

**Pull request closed without merging**
