### PR TITLE
Regenerate genrateDS with Python3, add CI to test generation, drop json serialisation (doesn't work with lxml), add generic `add` method

### PR DESCRIPTION
**Pull request by sanjayankur31**
Generates fine, and all tests pass using pytest.

### CODE REVIEW

**Comment by dkuhlman** [comment]
The change that eliminated the use of the XML library in the standard Python library (`xml.etree.ElementTree`) was made in gDS v.2.39.4 (revision 488 in the Mercurial repo of generateds at SourceForge.net.  You can see it with:

````
$ hg diff --rev 487 --rev 488 generateDS.py
````

Do we need another command line option that would enable you to generate modules that can use `xml.etree.ElementTree` if it is available (if it can be imported)?  Or, perhaps use it unconditionally?  That might be a messy change, but I think I could do that.

Or have you tracked this problem down to another source?

I worry about generating modules that can use `xml.etree.ElementTree`.  I believe that there have been problems reported with that.

Dave

**Comment by sanjayankur31** [comment]
Thanks @dkuhlman 

No, I haven't managed to narrow it down yet. I've just found all of these posts suggesting that lxml doesn't do well with pickling (also found one or two bugs about the python xml library not supporting pickling but these have been fixed now). There are a few moving parts here so I'll need to spend sometime debugging this. 

I guess I could start with testing the older version of generateDS that you've noted here and see how that does.

Thanks again for all your help :)

**Comment by sanjayankur31** [comment]
I tried it with generateDS-2.39.3 but it looks like there are bits in lxml.etree that aren't available in xml.etree.ElementTree. So, we get errors of this form:

```
Exception: ("Not a valid NeuroML 2 doc (/home/asinha/Documents/02_Code/00_mine/2020-OSB/NeuroML-software/libNeuroML/neuroml/test/../examples/test_files/simplenet.nml): 'xml.etree.ElementTree.Element' object has no attribute 'prefix'", AttributeError("'xml.etree.ElementTree.Element' object has no attribute 'prefix'"))
```

So I think we're perhaps better off just using lxml, and we'll drop bits that cannot be done with lxml, like the json serialization. I'll try and dig in more to see if this is indeed lxml related---it's just hard to come up with a simple test case to debug that and lxml is used in `generateds_config.py` etc. too, so maybe that's involved in the bug too. 

On my list of things to do :)

Here's the head of the generated nml.py file for confirmation:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Generated Wed Sep 15 14:07:29 2021 by generateDS.py version 2.39.3.
# Python 3.9.7 (default, Aug 30 2021, 00:00:00)  [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
#
# Command line options:
#   ('-o', 'nml.py')
#   ('--use-getter-setter', 'none')
#   ('--silence', '')
#   ('--user-methods', 'helper_methods.py')
#
# Command line arguments:
#   NeuroML_v2.2.xsd
#
# Command line:
#   /home/asinha/.virtualenvs/generateds-39-2.39.3/bin/generateDS.py -o "nml.py" --use-getter-setter="none" --silence --user-methods="helper_methods.py" NeuroML_v2.2.xsd
```
I'm collecting all of this debugging work in my fork here:

https://github.com/sanjayankur31/libNeuroML/tree/debug/generateds-2.39.3

**Comment by sanjayankur31** [comment]
libneuroml-docs


This is what the API documentation looks like at the moment

**Comment by sanjayankur31** [comment]
This is also ready for review + merge now. This is what the API documentation now looks like:

nml-api-docs

**Comment by pgleeson** [comment]
Looks good, but some tests still failing. All good to go?

**Comment by sanjayankur31** [comment]
Python 2.7 related issues in generateDS and some assertions used in tests that are py3 only. The assertions can be fixed with conditionals, but not sure what needs to be done for the generateDS bits :thinking:

**Comment by dkuhlman** [comment]
Ankur,

What are the Python 2.7 related issues in generateDS?  Is this something I can help with?

Dave

**Comment by sanjayankur31** [comment]
Hi @dkuhlman 

There are a few tracebacks in the CI of this form:

```
    def export(
        self,
        outfile,
        level,
        namespaceprefix_="",
        namespacedef_="",
        name_="IafCell",
        pretty_print=True,
    ):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get("IafCell")
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = "\n"
        else:
            eol_ = ""
        if self.original_tagname_ is not None and name_ == "IafCell":
            name_ = self.original_tagname_
        if UseCapturedNS_ and self.ns_prefix_:
            namespaceprefix_ = self.ns_prefix_ + ":"
        showIndent(outfile, level, pretty_print)
        outfile.write(
            "<%s%s%s"
            % (
                namespaceprefix_,
                name_,
>               namespacedef_ and " " + namespacedef_ or "",
            )
        )
E       TypeError: unicode argument expected, got 'str'
```

I need to look into our schema, in case any of our recent changes may be causing it.

**Comment by sanjayankur31** [comment]
@dkuhlman : It does seem to be from the generateDS generated code, so I opened an issue on Sourceforge here: https://sourceforge.net/p/generateds/tickets/28/

**Comment by sanjayankur31** [comment]
@pgleeson tweaked nml.py to get all tests to pass now.

**Comment by pgleeson** [comment]
Looks goog, tested locally @sanjayankur31

**Pull request merged**
