### PR TITLE
Py3

### LINKED ISSUE #58: Make generated API Python 3 compatible
A change is required to [generateDS.py](http://www.davekuhlman.org/generateDS.html)  for this.

@rgerkin is working on this here: https://bitbucket.org/dkuhlman/generateds/pull-request/13/changes-for-python-3-compatibility/diff

### PR DESCRIPTION
**Pull request by clbarnes**
Resolves #58, sort of.

It required removing `simplejson` from the test environment for 3.5 - I don't know how much of a performance hit this is, but the py3 tests run about 5s slower than 2.7. However, I'd rather have a version which at least works on the current and future version of the language and open a new issue for the speedup than just leave it, if simplejson isn't an absolute requirement.

There is still an issue with `jsonpickle` - something to do with decoding of unicode strings - but bumping the requirement down to 0.7.2 fixes that.

I also shaved about 30% off the build time by installing the optional dependencies with conda instead of pip. I suspect it'd be faster still if I conda install'd `lxml` but I thought I'd stick with pip for the dependency which `setup.py` would drag in through pip in production.

However, I think it would be a good idea to have an `optional_requirements.txt` which lists all of the... well, optional requirements. Then it's nice and explicit for anyone who wants a green testing board and it's clear to see what is and isn't necessary for the 'full' libNeuroML experience. But we'd lose the build speedup.

Let me know what you think about 

- [ ] use of conda in CI
- [ ] the simplejson exclusion
- [ ] the possible `optional_requirements.txt`

### CODE REVIEW

**Comment by pgleeson** [comment]
@clbarnes thanks for this PR. I've not had a chance to look at it this yet, but try it out early next week.

**Comment by clbarnes** [comment]
No worries - for all the many commits the changes to get the build passing are actually very minor.

**Comment by pgleeson** [comment]
Thanks @clbarnes, merged finally. 

optional_requirements.txt seems like a good idea. Would this be used in the .travis.yml, or just used for information?

**Comment by clbarnes** [comment]
It just depends on what we want to exercise in the unit tests, really - it would even be possible to do both by setting up two conda environments, one with and one without the optionals, then run the unit tests in each.

The main benefit would be allowing users to easily discriminate between obligatory and optional dependencies and install both easily.. I don't know if it's possible to get setup.py to install one, and then attempt to install the other without erroring.

**Pull request merged**
