### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by sanjayankur31**
Lots of minor fixes to the docs. It also now generates the API documentation (which we'll link to from docs.neuroml.org).

### CODE REVIEW

**Comment by sanjayankur31** [comment]
@pgleeson : this should be ready now. I've added docstrings to all the helper methods and they get picked up by sphinx now. (Please do take a look at the docstrings and correct/improve them though)

**Comment by sanjayankur31** [comment]
Eh: looks like the new generateDS run has broken something. Looking into it now.

**Comment by sanjayankur31** [comment]
The API being generated by generateDS is now different:

For example, instead of "includes", it's now generating "include":

``` diff
-        MemberSpec_('includes', 'IncludeType', 1, 1, {u'maxOccurs': u'unbounded', u'type': u'IncludeType', u'name': u'include', u'minOccurs': u'0'}, None),
+        MemberSpec_('include', 'IncludeType', 1, 1, {'maxOccurs': 'unbounded', 'minOccurs': '0', 'name': 'include', 'type': 'IncludeType'}, None),

```

Looking for its change log now to see how this sort of thing is to be handled.

**Comment by pgleeson** [comment]
FYI `include` is a special case as there are 2 elements called include (include a file and an include in a segment group) and there was some code to force one to somethign different i recall...

**Comment by sanjayankur31** [comment]
@pgleeson it needed some tweaks to the `generateds_config.py` file. Now I've got a test failing because in the various generated classes, there isn't a definition of the `add_anytypeobjs_` methond. For example:

```
AttributeError: 'Annotation' object has no attribute 'add_anytypeobjs_'
```

If I do not use `--use-getter-setter=none`, this is included in the nml.py file. Is there a reason we use `--use-getter-setter=none`?

I also see that the version in master doesn't include the `add_anytypeobjs_` method either, but the call isn't ever reached so we don't get the failing test there :thinking:

**Comment by sanjayankur31** [comment]
The `add_anytypeobjs()` method is added here, but only if getters/setters are included:

https://sourceforge.net/p/generateds/code/ci/default/tree/generateDS.py#l5983

So this particular issue can be solved by removing the `--use-getter-setter=none` bit. Then, we run into another error, though.

**Comment by pgleeson** [comment]
Have you tried generating with py2.7 with the stated verson of generateds & existing helper/config files? That generates a usable nml.py in py 2 & py3... Saves going down the rabbit hole for another time...

**Comment by sanjayankur31** [comment]
> Have you tried generating with py2.7 with the stated verson of generateds & existing helper/config files? That generates a usable nml.py in py 2 & py3... Saves going down the rabbit hole for another time...

Not yet, I'll go try that out in a different branch and see what I get. 

I've "fixed" nml.py now to pass all tests and filed an issue with upstream: https://sourceforge.net/p/generateds/tickets/13/
So we should know soon where the issue is with the new version.

Now the json serialization example fails, though. :laughing:

**Comment by sanjayankur31** [comment]
@pgleeson : reverted to py2.7 + the older generateDS, so this is ready for review + merge now.

Will keep looking into py3 and new generateds on the side when possible.

**Comment by pgleeson** [comment]
@sanjayankur31 Good old python 2! And you wanted to obliterate it... 😃

**Review by pgleeson — APPROVED** [review]
Looks good!

**Pull request merged**
